### ISSUE TITLE
Shader axis

### ISSUE THREAD

**Issue by jeekca** [lachlanmcdonald/magicavoxel-shaders#20]
Hey guys,

I was wondering if it was possible to choose the axis of the shader?

I don't know if I'm missing something, but after lots of researching and trying out different things, I can't seem to find a way to get your voxel shaders (brushes in this instance) to work on a wall (Y axis only). I don't know if this is due to a lack of understanding MagicaVoxel or something else, but it seems that all of your brushes work as expected when applied a surface over the Z axis, but when applied on a wall, they all end up as straight vertical lines.

I'm on MagicaVoxel 0.99.6.2 and working with the shaders' latest master branch.

Thanks a ton!

**Comment by lachlanmcdonald** [comment]
Hi @jeekca;

1. If you want to restrict the shaders to a particular axis, see #21 (only a few shaders can be restricted to a particular axis)
2. To restrict the shaders to only certain voxels, you have a [look at the documentation](https://github.com/lachlanmcdonald/magicavoxel-shaders/wiki/Brush-Shaders)
