### ISSUE TITLE
Cover Shader. How it works? 

### ISSUE THREAD

**Issue by PiotrBablok** [lachlanmcdonald/magicavoxel-shaders#27]
Hello. I'll start by saying that contacting you is the last option left for me. I can not cope with the shader from your package, namely 'cover'. I have no idea how to use it to work as you show in the examples on the wiki. Can you explain to me how it works? I'm probably too stupid to use it and am doing something wrong, but I can't find anywhere an example of how others work with this shader.
![Bez tytułu](https://user-images.githubusercontent.com/62600708/130529515-6ddcb547-6485-4751-aeeb-0ef479600452.png)

**Comment by PiotrBablok** [comment]
It could be that this shader is not working. I contacted other MagicVoxel users about this and the latest version does not work for them either.

**Comment by ericschn** [comment]
Removing the clamp function allows it to work on nVidia hardware for me.

**Comment by PiotrBablok** [comment]
That's right. Now it works without any problem :)

Just swap: 
float headroom = clamp(1.0, 255.0, m_headroom);
float noise = clamp(0.0, 1.0, m_noise);

To: 
float headroom = m_headroom;
float noise = m_noise;

Thank you for your help :)

**Comment by lachlanmcdonald** [comment]
Removed `clamp` from the shaders to avoid issues until I can investigate why. Will be part of 0.12.0 release.
