### ISSUE TITLE
Shader documentation incorrect

### ISSUE THREAD

**Issue by pentool** [lachlanmcdonald/magicavoxel-shaders#38]
In the shader documentation under the _"Parameters"_ section you write _"...In previous versions of MagicaVoxel, there was a limit to the number of parameters which could be passed to a shader. In current versions, this limit no longer applies."_

It would be nice to mention which _"versions"_ are we talking about. Also, on which platform(s) was this statement concluded. As of March 30, 2022 I am using the latest version of MV on the Mac (0.99.6.2) and the number of parameters are maxing out at 16!!!

**Comment by lachlanmcdonald** [comment]
You are correct, there seems to be an upper limit of 16 parameters. Even if the shader compiles, any parameters after the 16th will not be accessible. Will update the docs.
