### ISSUE TITLE
Combine brick with outline for masonary?

### ISSUE THREAD

**Issue by cacoe** [lachlanmcdonald/magicavoxel-shaders#6]
Hi, I know there hasn't been much contribution to this for a while, however I think it would be very helpful to be able to create masonry lines around the bricks, is anyone about to create this shader at all? I would greatly appreciate it!

**Comment by lachlanmcdonald** [comment]
Complete. This will be part of the next release.

**Comment by lachlanmcdonald** [comment]
@cacoe, grout is now part of the [Brick shader](https://github.com/lachlanmcdonald/magicavoxel-shaders/wiki/Brick-Brushes) in the latest release.
